# Generated by Django 3.2.6 on 2021-08-11 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('predictor', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='covidlist',
            name='covid',
            field=models.CharField(default=0, max_length=5),
            preserve_default=False,
        ),
    ]
